---
language: "python"
python:
  - "3.6"
  - "3.7"
  - "3.8"
# Add your encrypted secret below, you can encrypt secret using "travis encrypt"
# https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
# global:
#   secure: <Add encrypted token>
services:
  - "docker"
# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
  - "pip install invoke docker-compose"
  - "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py"
  - "python /tmp/get-poetry.py -y --version 1.1.6"
  - "source $HOME/.poetry/env"
  - "cp development/creds.example.env development/creds.env"

script:
  # If you want to test different versions, it may require updating the poetry definition for Nautobot
  # as that is where the version is controlled
  # - "poetry add nautobot=$NAUTOBOT_VER"
  - "INVOKE_VIP_TRACKER_PYTHON_VER=$TRAVIS_PYTHON_VERSION invoke build --no-cache"
  - "INVOKE_VIP_TRACKER_PYTHON_VER=$TRAVIS_PYTHON_VERSION invoke tests --failfast"
# --------------------------------------------------------------------------
# Deploy
#  Uncomment the section below if you would like to publish a new release to pypi automatically
#  when a new tag is created in master. You"ll also need to generate a dedicated API key for this project in pypi
#  and encrypt the key with "travis encrypt PYPI_TOKEN=<value> --add env.global --com"
# --------------------------------------------------------------------------
# deploy:
#   provider: script
#   script: poetry config pypi-token.pypi $PYPI_TOKEN && poetry publish --build
#   skip_cleanup: true
#   on:
#     tags: true
#     branch: master
#     condition: $NAUTOBOT_VER = master
#     python: 3.7
