---
version: "3.8"
services:
  netconf1:
    container_name: "netconf1"
    hostname: "netconf1"
    image: "sysrepo/sysrepo-netopeer2:latest"
    ports:
      - "1830:830"
    environment:
      NACM_RECOVERY_UID: "0"
  test:
    container_name: "test"
    hostname: "test"
    build:
      context: "."
      target: "test"
    depends_on:
      - "netconf1"
      # volumes:
      #   - "./:/usr/src/app"
