---
version: "3.8"
services:
  netconf_sysrepo:
    container_name: "netconf_sysrepo"
    hostname: "netconf_sysrepo"
    image: "sysrepo/sysrepo-netopeer2:latest"
    ports:
      - "1830:830"
    environment:
      NACM_RECOVERY_UID: "0"
  test:
    container_name: "test"
    hostname: "test"
    build:
      context: "."
      target: "test"
    depends_on:
      - "netconf_sysrepo"
      # volumes:
      #   - "./:/usr/src/app"
  clab:
    image: "ghcr.io/srl-labs/clab"
    network_mode: "host"
    working_dir: "/src"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/netns:/var/run/netns"
      - "/etc/hosts:/etc/hosts"
      - "./:/src"
      - "./clab-topo-netconf.yml:/src/clab-topo-netconf.yml"
    pid: "host"
    command: "containerlab deploy -t clab-topo-netconf.yml"
    # If you want to destroy the lab, ovveride the command while executing docker-compose service
    # docker-compose run clab containerlab destroy -t clab-topo-netconf.yml
    privileged: true
    tty: true
