---
version: "3.8"
services:
  netconf1:
    container_name: "netconf1"
    hostname: "netconf1"
    image: "sysrepo/sysrepo-netopeer2:latest"
    ports:
      - "830:830"
  netconf3:
    container_name: "netconf3"
    hostname: "netconf3"
    image: "sysrepo/sysrepo-netopeer2:latest"
    ports:
      - "830:830"
  test:
    container_name: "test"
    build:
      context: "."
      target: "test"
    depends_on:
      - "netconf1"
