---
site_name: "Nornir NETCONF Documentation"
site_url: "https://nornir-netconf.readthedocs.io"
repo_url: "https://github.com/h4ndzdatm0ld/nornir_netconf"
theme:
  name: "readthedocs"
  navigation_depth: 3
nav:
  - Introduction: "index.md"
  - Inventory Plugin: "inventory/inventory.md"
  - Processor Plugin: "processor/processor.md"
  - Task Plugin: "task/task.md"