---
name: "Nornir NETCONF"

on:
  push:
    branches: ["*"]

jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Lint & Code Format
        run: |
          echo 'Running Flake8' && \
          poetry run flake8 . && \
          echo 'Running Black' && \
          poetry run black --check --diff . && \
          echo 'Running Yamllint' && \
          poetry run yamllint . && \
          echo 'Running pydocstyle' && \
          poetry run pydocstyle . && \
          echo 'Running Bandit' && \
          poetry run bandit --recursive ./ --configfile .bandit.yml && \
          echo 'Running MyPy' && \
          poetry run mypy .

  test:
    name: Testing on Python ${{ matrix.python-version }}
    runs-on: self-hosted
    env:
      SKIP_INTEGRATION_TESTS: True
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Down Docker!
        run: docker-compose down

      # - name: Be Gone!
      #   run: sudo rm -rf clab-clab-topo-netconf.yml/

      # - name: Reset Permissions from Root
      #   run: sudo chown -R htinoco .

      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Reset Permissions from Root
        run: sudo chown -R htinoco .

      # - name: Rebuild
      #   run: docker-compose build

      - name: Start Containerlab
        run: docker-compose run clab containerlab deplopy -t clab-topo-netconf.yml  --reconfigure

      - name: Sleep for 200 seconds
        run: sleep 200s
        shell: bash

      - name: Pytest
        run: docker-compose run test

      - name: Reset Permissions from Root
        run: sudo chown -R htinoco .

      - name: Destroy Container Lab
        run: docker-compose run clab containerlab destroy -t clab-topo-netconf.yml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
